FROM debian:bookworm-slim

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ca-certificates curl git bash tini chromium \
    && rm -rf /var/lib/apt/lists/*

ENV SB_HOSTNAME=0.0.0.0 \
    SB_FOLDER=/space \
    SB_PORT=3000 \
    CHROMIUM_PATH=/usr/bin/chromium

EXPOSE 3000
HEALTHCHECK CMD curl --fail "http://localhost:$SB_PORT$SB_URL_PREFIX/.ping" || exit 1

COPY silverbullet-gnu-amd64 /silverbullet
RUN chmod +x /silverbullet
ENTRYPOINT ["/usr/bin/tini", "--", "/silverbullet"]
